im trying
package-lock.json
File
-----> Building on the Heroku-24 stack
-----> Determining which buildpack to use for this app
-----> Node.js app detected

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):   unspecified
       engines.npm (package.json):    unspecified (use default)

       Resolving node version 20.x...
       Downloading and installing node 20.18.0...
       Using default npm version: 10.8.2

-----> Installing dependencies
       Installing node modules

       added 191 packages, and audited 192 packages in 3s

       37 packages are looking for funding
         run npm fund for details

       7 vulnerabilities (3 low, 2 moderate, 2 high)

       To address issues that do not require attention, run:
         npm audit fix

       To address all issues (including breaking changes), run:
         npm audit fix --force

       Run npm audit for details.
       npm notice
       npm notice New minor version of npm available! 10.8.2 -> 10.9.0
       npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
       npm notice To update run: npm install -g npm@10.9.0
       npm notice

-----> Build
       Running build

       > client-db@0.0.1 build
       > vite build

       vite v5.2.11 building SSR bundle for production...
       transforming...
       ✓ 93 modules transformed.
x Build failed in 309ms
error during build:
RollupError: src/lib/server/database.js (5:8): "PGCONNECT" is not exported by "virtual:$env/static/private", imported by "src/lib/server/database.js".
file: /tmp/build_4cb73e9f/src/lib/server/database.js:5:8
3:
4: // see env variables in .env
5: import {PGCONNECT} from '$env/static/private';
           ^
6:
7: const sql = postgres(PGCONNECT, {} )
    at getRollupError (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at error (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/parseAst.js:390:42)
    at Module.error (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/node-entry.js:13855:16)
    at Module.traceVariable (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/node-entry.js:14303:29)
    at ModuleScope.findVariable (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/node-entry.js:11984:39)
    at Identifier.bind (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/node-entry.js:6908:40)
    at CallExpression.bind (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/node-entry.js:4771:28)
    at CallExpression.bind (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/node-entry.js:9135:15)
    at VariableDeclarator.bind (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/node-entry.js:4775:23)
    at VariableDeclaration.bind (file:///tmp/build_4cb73e9f/node_modules/rollup/dist/es/shared/node-entry.js:4771:28)
-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       Some possible problems:

       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

       Love,
       Heroku

 !     Push rejected, failed to compile Node.js app.
 !     Push failed